### ISSUE TITLE
Node.js 16 actions are deprecated. Upgrade to Node.js 20.

### ISSUE THREAD

**Issue by tpcarman** [Eomm/why-don-t-you-tweet#103]
The following warning is shown when running the GitHub Action workflow.

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Eomm/why-don-t-you-tweet@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by Eomm** [comment]
Thanks for reporting!
Would you like to send a Pull Request to address this issue?
